### PR TITLE
DAG fails to render if operation exists

### LINKED ISSUE #229: DAG fails to render if operation (`on-run-*` hook) has parents
### Describe the bug
If an operation (`on-run-*` project hook) depends on a model, it creates an entry for that operation in `parent_map` + `child_map` in `manifest.json`, which throws off the DAG rendering logic. It is possible to still use the DAG viz by adding `--select` criteria, i.e. by filtering out the operation node.

It's arguable whether operations should be included in `parent_map` + `child_map`, but isn't strictly wrong that they are. Changing that would require an artifact schema change. For now, it feels appropriate to handle this in the `dbt-docs` DAG rendering logic.

### Steps To Reproduce
```yml
# dbt_project.yml
on-run-end:
  - "{{ reference_my_model() }}"
```
```sql
-- macros/reference_my_model.sql
{% macro reference_my_model() %}

    select 1 from {{ ref('my_model') }}

{% endmacro %}
```
```sql
-- models/my_model.sql
select 1 as id
```

```
$ dbt docs generate
$ dbt docs serve
```

Screenshot 2022-01-10 at 21 23 27

I haven't been able to successfully run `npm` on this machine, so I can't generate source maps and get a more helpful pointer to a specific line of code. That's definitely the thing to do first.

**The output of `dbt --version`:**
This fails in v1.0.1 and v0.21.1, so at least this isn't a regression in v1.0. But it's pretty obnoxious, and I bet the fix is straightforward, so I'd like to include in dbt-core==1.0.2 if we can.

### PR DESCRIPTION
**Pull request by emmyoop**
resolves #229 

### Description

Adds operations so that parent/child map can be resolved.  Also added the ability to view operations so SQL can be viewed.  Previously operations linked to no where.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have generated docs locally, and this change appears to resolve the stated issue
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: src/app/components/references/index.js [hunk 1]
```diff
@@ -45,6 +45,8 @@ angular
                       return 'Exposures';
                 } else if (type == 'metric') {
                       return 'Metrics';
+                    } else if (type == 'operation') {
```
Comment (leahwicz) [inline src/app/components/references/index.js:48]: Nit: the indentation looks off here

**Review by leahwicz — APPROVED** [review]
