### PR TITLE
Fix for column tests not rendering on quoted columns

### LINKED ISSUE #201: `quote: true` for column in `.yml` properties causes tests not to render in TESTS column in the Column table
Given model `docs_test.sql` with:
```
select 'foo' as "My Space", 'bar' as "NoSpace"
```

and `docs_test.yml` with:
```
version: 2

models:
  - name: docs_test
    columns:  
      - name: My Space
        quote: true
        tests:
        - not_null
      - name: NoSpace
        quote: true
        tests:
        - not_null
```

a `dbt docs generate` runs but when I got to view docs I don't see docs for either referenced under the TESTS column in the Columns table in the browser.

This code in the underlying javascript `<!-- ngIf: has_test(column, 'N') -->` doesn't seem to be able to find the column when quote: true is applied.   [That source is here.](https://github.com/dbt-labs/dbt-docs/blob/master/src/app/components/column_details/column_details.js#L17-L20).

Screen Shot 2021-07-08 at 4 56 24 PM

Things I tried to work around:
- Removing quote works for docs, but then breaks the test since I need to preserve lettercase and/or the space here.
- Adding quotes to name: like `"'My Space'"` allows the test to work, but results in a double entry in docs.

Screen Shot 2021-07-08 at 5 02 14 PM

### PR DESCRIPTION
**Pull request by drewbanin**
resolves #201

### Description

Quoted columns are rendered with explicit quotes in the manifest.json file. These quotes prevent the dbt-docs site from matching a column name from the manifest (attached to a model) with a test node relevant to that column. Here's an example test node in the manifest for a quoted column:

```yml
        "test.my_new_project.not_null_quoted_ident__TEST_2_COLUMN_.f762812d7c": {
            "test_metadata": {
                "name": "not_null",
                "kwargs": {
                    "column_name": "\"TEST_2_COLUMN\"",
                    "model": "{{ get_where_subquery(ref('quoted_ident')) }}"
                },
                "namespace": null
            },
            "database": "ANALYTICS",
            ...
            "config": {...},
            "compiled_code": "select \"TEST_2_COLUMN\"\nfrom ANALYTICS.dbt_dbanin.quoted_ident\nwhere \"TEST_2_COLUMN\" is null",
            "column_name": "\"TEST_2_COLUMN\"",
            "file_key_name": "models.quoted_ident",
            "attached_node": "model.my_new_project.quoted_ident"
        }
```

It is probably worth exploring a change to the dbt-core implementation in the future. I imagine we could instead leave the column_name field unquoted, but include a boolean `column_is_quoted` flag, or similar. That would make string processing a little bit easier, as well as help us account for different quoting styles across data platforms more readily.

In the meantime, this PR works by stripping quotes from the `column_name` before performing a case-insensitive match across model node + test node.

### Checklist

- [x] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me
- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] I have [opened an issue to add/update docs](https://github.com/dbt-labs/docs.getdbt.com/issues/new/choose), or docs changes are not required/relevant for this PR
- [x] I have run `changie new` to [create a changelog entry](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md#Adding-CHANGELOG-Entry)

### CODE REVIEW

File: src/app/services/project_service.js [hunk 1]
```diff
@@ -228,7 +228,13 @@ angular
                     }
                     var node = project.nodes[model];
                     var column = _.find(node.columns, function(col, col_name) {
-                        return col_name.toLowerCase() == test_column.toLowerCase();
+                        // strip quotes from start and end of test column if present in both locations
+                        // this is necessary to attach a test to a column when `quote: true` is set for a column
+                        let test_column_name = test_column;
+                        if (test_column.startsWith('"') && test_column.endsWith('"')) {
```
Comment (jtcohen6) [inline src/app/services/project_service.js:234]: Quote characters are different on different adapters. E.g. on `dbt-bigquery` it will be:
```json
  "column_name": "`id`",
```

It is less common to quote columns on BQ, since it doesn't generally support spaces / special characters — but it does still support reserved keywords (e.g. `from`) as column names if quoted.

I'm not sure if there's a cleverer regex check we could/should be doing here instead of hard-coding `"`

**Review by jtcohen6 — COMMENTED** [review]
It is odd that we resolve the quoting before storing the values in the manifest, rather than hanging onto the original (unquoted) `column_name` and `quote: true` parameter

File: src/app/services/project_service.js (hunk 1 above)
Comment (drewbanin) [reply src/app/services/project_service.js]: Just pushed another commit here. I tried to go the regex route, but i think it was a little too complicated. The specific problem is that I wanted to ensure that the start and end quote chars are the same (eg. we shouldn't strip quotes from the string `` "some_column` ``). I ended up enumerating different quote chars based on data platform in the javascript. I made the backtick BQ-only, which is not correct, but wondering if it's close enough?

Other thoughts:
- I am very open to other suggestions/ideas on how to handle this, or just a statement that "this ain't it" and i'll have a harder think about it :)
- Can you confirm my assumption that the `metadata.adapter_type` field will read "bigquery" on bigquery?
- Really reinforcing my desire for some sort of adapter-specific info within the manifest. That could look like including quote chars in the `metadata` blob to avoid needing to encode this sort of info in js!

Comment (jtcohen6) [reply src/app/services/project_service.js]: `spark` & `databricks` also use backticks as quotes :)

Agree this isn't _really_ scalable to other adapters! It could make sense to include this kind of "static" adapter-specific info somewhere in the manifest — though if I had to pick between doing that, and including the original unquoted `column_name` value on the test node, I have a slight preference for the latter

Comment (jtcohen6) [reply src/app/services/project_service.js]: at the end of the day - I'm fine with this approach for the time being

Comment (drewbanin) [reply src/app/services/project_service.js]: ok - just added the same logic for spark + databricks and a test too! 🏓

**Review by jtcohen6 — APPROVED** [review]
lgtm! :)

press "go" at your leisure, and then trigger [this action](https://github.com/dbt-labs/dbt-docs/actions/workflows/generate-docs-for-dbt-core.yml) (unless you'd rather I do it)
