### PR TITLE
CT-50 Search results not filtering correctly

### LINKED ISSUE #236: [CT-157] [Bug] Search in generated docs is not filtering as expected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Customer is using Databricks in dbt Cloud. When docs are generated during their production run, user is seeing no change in the search results when they attempt to filter by their search query. 

Secondary issue is that the displayed model size is incorrect. (Ex. model is showing as 23GB in docs, while it's ~8MB in Databricks)

### Expected Behavior

Results should be filtered by an inputed search term or query. Also if no results, it should not be showing all available items.

### Steps To Reproduce

1. Log into customer account and open Documentation.
2. Attempt to search (ex. fct_credit_test).
3. All results are displayed.

### Relevant log output

_No response_

### Environment

```markdown
- dbt: 1.0
```

### What database are you using dbt with?

other (mention it in "Additional Context")

### Additional Context

Databricks

### PR DESCRIPTION
**Pull request by emmyoop**
resolves #236 

### Description

Search results not filtering correctly.  This is actually a [bug in dbt-spark](https://github.com/dbt-labs/dbt-spark/issues/295).  This fix makes it so docs continue to work by checking for conditions that should never be true.

This way, once the bug is fixed, docs will continue to work as expected and will continue to work for all other adapters.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have generated docs locally, and this change appears to resolve the stated issue
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: src/app/components/model_tree/model_tree_line.js [hunk 1]
```diff
@@ -25,6 +25,13 @@ angular
             // start = everything up to end
 
             var name = scope.item.name;
+
+            // name *should* always exists but there is a bug where some items don't make it into the catalog.
```
Comment (leahwicz) [inline src/app/components/model_tree/model_tree_line.js:29]: Is there an issue for that bug that we could link here so its easy to see if it's finally resolved?

**Review by leahwicz — APPROVED** [review]
