### PR TITLE
Fix the sample SQL when the source has no database

### LINKED ISSUE #264: databricks sample SQL has a dot before the schema name
### Describe the bug
When using the **[dbt-databricks](https://github.com/databricks/dbt-databricks)** adapter, the Sample SQL generated by dbt-docs (core version v1.0.1) contains a dot before the relation name, **[Yikun Song reports on dbt Slack](https://getdbt.slack.com/archives/CBSQTAPLG/p1650456653012479)**. This makes the query invalid.

```sql
SELECT
...
FROM .clean__schema_name.table_name
```

### Expected behavior
The relation should be referenced without the leading dot, as e.g. `FROM clean__schema_name.table_name`

### Why is this happening?
As Benoit says
> There is a dot because normally dbt is providing the format database.schema.table but I think that databricks/spark do not use a concept of database

The [`generateSourceSQL` function in code_service.js](https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/services/code_service.js#L52) has the faulty logic:
`var rel = [model.database, model.schema, model.identifier || model.alias || model.name].join(".");`

### Suggested fix

As a fix, I’d suggest using the relation-building logic seen in `table_details.js`: https://github.com/dbt-labs/dbt-docs/blob/5f791fe466906df556855b0f2ac2fd9ff29019fc/src/app/components/table_details/table_details.js#L81-L95

### PR DESCRIPTION
**Pull request by b-per**
resolves #264 

### Description

Fix for the issue raised where the sample SQL Code is incorrect when the data source isn't linked to any database (like in databricks).

To test it, I updated the database field in my `manifest.json`, replacing `"jaffle_shop"` by `""`.

Behaviour before the change, when no DB is defined:
image

Behaviour after the change, when no DB is defined:
image

Behaviour after the change, when a DB is defined:
image

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have generated docs locally, and this change appears to resolve the stated issue
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

File: src/app/services/code_service.js [hunk 1]
```diff
@@ -49,7 +49,16 @@ angular
...
-        var rel = [model.database, model.schema, model.identifier || model.alias || model.name].join(".");
+        var database;
+        if (!model.database) { 
+            database = '' 
+        } else {
+            database = model.database + '.'
+        }
+
+        var rel;
+        rel = database + model.schema + "." + model.identifier;
```
Comment (stu-k) [inline src/app/services/code_service.js:60]: Nonblocking, but this can be cleaned up a bit:
```suggestion
        const database = model.database ? model.database + '.' : '';
        const rel = database + model.schema + "." + model.identifier;
```

Comment (b-per) [reply src/app/services/code_service.js:60]: I was wondering if it should be written in a more "javascript" way or following the existing code base 😄

**Review by stu-k — APPROVED** [review]
LGTM! 👍

**Review by emmyoop — CHANGES_REQUESTED** [review]
Looks good.  I tested locally and it works as expected!  

This is going to go in to `1.2.0`.  If you pull in recent changes, there's a spot in the `CHANGELOG` for that now.  Please update your `CHANGELOG` entry to be under the accurate release and I'll get this merged in.  Also, don't forget to add yourself under Contributors 😃 

Thank you so much for the contribution @b-per!

**Review by emmyoop — APPROVED** [review]
Looks good.  Thanks again!

**Comment by martinburch** [comment]
Sorry, bit late to this, and many thanks to the reviewers, but is it ok that this code will now require model.identifier whereas the old code tried to use model.identifier, model.alias, or model.name?

**Comment by b-per** [comment]
I think that it is OK, yes. 
The previous code was more generic and had some logic that could apply to models as well as sources. The bit of code changed is actually only executed for sources so we don't have to worry about alias (which don't apply to sources) and so on.
